### ISSUE TITLE
Disable on release build

### ISSUE THREAD

**Issue by YoungjaeKim** [zserge/log#11]
Hi.
I came here from your comment http://stackoverflow.com/questions/2446248/remove-all-debug-logging-calls-before-publishing-are-there-tools-to-do-this#comment49537599_26462092

Refer to the original post question, how to disble log printing for Release build only?

**Comment by zserge** [comment]
@YoungjaeKim The easiest would be to do is explicitly with code:

```
if (!BuildConfig.DEBUG) {
  Log.usePrinter(Log.ANDROID, false); // from now on Log.d etc do nothing and is likely to be optimized with JIT
}
```

You can put it into your Application code or in your main activity

**Comment by YoungjaeKim** [comment]
Thanks for the quick reply.
I suggest [Readme.md PR](https://github.com/zserge/log/pull/12).
