### ISSUE TITLE
Feature Request: replaceable implementation

### ISSUE THREAD

**Issue by KennyGoers** [zserge/log#4]
One thing I really liked about Timber was the ability to replace the log implementation, especially for release level, I use Crashlytics and it would be AWESOME to be able to replace the actual log target with a separate implementation I could direct.

**Comment by zserge** [comment]
If you mean a public interface to provide your own log "printer" - that should not be hard to add. Log now supports `System.out.println` and `android.util.Log` as backends, but they are dispatched by a simple if/else statement. Putting them under a common interface and keeping a list of such printers is all that's needed if I understood your request correctly.

**Comment by KennyGoers** [comment]
I think so, just to create an interface instead of the if/else
implementation and just implement those very simple interfaces... Timber
does a good job of it if you'd want to take a peek.

**Comment by zserge** [comment]
Timber seems to have a very large Tree interface (basically, all logging control seems to be delegated to the implementation). I decided to only leave the output function up to the implementation. You may check the most recent commit. There is a `Log.Printer` interface, you may implement it and call `Log.usePrinter(myPrinter, true)`. Let me know if that works for you.
