### ISSUE TITLE
Is all debug logging calls automated being removed? (Question)

### ISSUE THREAD

**Issue by joielechong** [zserge/log#6]
Is all debug logging calls automated being removed when building a release version with Android Studio or we must add proguard rules to remove log?

**Comment by zserge** [comment]
No, this library uses a different approach. I personally don't think that stripping classes and methods off of the app byte code is a good way to disable logs. I prefer something more readable and explicit like `if release then disableLogs` in Java code.

So in your Application class (or any static initializer block of any other class) you can do `if (!BuildConfig.DEBUG) Log.level(Log.E);` to only leave error messages in release builds. Or `Log.E+1` (I probably should define it as a constant Log.NONE) to disable all the logs. In this case Log.d() calls would do only one conditional check and return immediately. Most likely these calls would be optimized well enough by AOT or JIT.

**Comment by joielechong** [comment]
Okay then, thanks for the information.
